CREATE TABLE LOGDOWNLOAD(
  CODIGO NUMERIC(22,0) NOT NULL, 
  URL VARCHAR2(600) NOT NULL,
  DATAINICIO DATE NOT NULL,
  DATAFIM DATE,
  PERCENTUAL INTEGER DEFAULT 0 NOT NULL, 
  CONSTRAINT PK_LOGDOWNLOAD PRIMARY KEY (CODIGO)
);